# Generated by Django 5.1 on 2026-05-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFitScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_key', models.CharField(max_length=50)),
                ('plan_key', models.CharField(max_length=50)),
                ('use_case', models.CharField(choices=[('coding', 'Coding'), ('writing', 'Writing'), ('data', 'Data / Analysis'), ('research', 'Research'), ('mixed', 'Mixed')], max_length=20)),
                ('score', models.IntegerField()),
                ('reasoning', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['use_case', '-score'],
                'unique_together': {('vendor_key', 'plan_key', 'use_case')},
            },
        ),
        migrations.CreateModel(
            name='VendorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_key', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=100)),
                ('plan_key', models.CharField(max_length=50)),
                ('plan_name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_seats', models.IntegerField(default=1)),
                ('max_seats', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('credex_eligible', models.BooleanField(default=False)),
                ('source_url', models.URLField()),
                ('last_verified', models.DateField()),
            ],
            options={
                'ordering': ['vendor_key', 'plan_key'],
                'unique_together': {('vendor_key', 'plan_key')},
            },
        ),
    ]
