# Generated by Django 5.1 on 2026-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='referred_by_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
